title: Meridith L. Bartley
disqusShort: mlbartley
logo: /images/front-self.jpeg
description: Statistical consulting for environmental and ecological applications. 
show_downloads: true
theme: jekyll-theme-minimal 
#theme: minimal-mistakes-jekyll
