title: Meridith L. Bartley
logo: /images/front-self.jpg
description: Statistical consulting for environmental and ecological applications. 
show_downloads: true
theme: jekyll-theme-minimal 
#theme: minimal-mistakes-jekyll
